### PR TITLE
Fix #95: Address Jest moduleDirectories Behavior

### LINKED ISSUE #95: `react-app-alias-ex` is not a drop-in replacement for `react-app-alias`
When using `react-app-alias-ex` to allow outside of root packages (a unique aspect of our setup) Jest throws resolver errors:

```
 FAIL  src/views/__tests__/BSListViewTemplate.test.js
  ● Test suite failed to run

    Cannot find module 'semver' from 'node_modules/jest-snapshot/build/InlineSnapshots.js'

    Require stack:
      node_modules/jest-snapshot/build/InlineSnapshots.js
      node_modules/jest-snapshot/build/State.js
      node_modules/jest-snapshot/build/index.js
      node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
```

But switching back to `react-app-alias` and temporarily commenting out our external packages works as expected.

**Config files:**

```json
// jsconfig.paths.js
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@utils/*": ["src/utils/*"],
            "@constants/*": ["src/constants/*"],
            "@views/*": ["src/views/*"],
            "@components/*": ["src/components/*"],
            "@layouts/*": ["src/components/layouts/*"],
            "@common/*": ["src/components/common/*"],
            "@core/*": ["src/components/core/*"],
            "@example_plugin/*": [
                "../../examples/example_plugin/example_plugin/ui/*"
            ]
        }
    }
}
```

```json
// jsconfig.js
{
    "extends": "./jsconfig.paths.json",
    "compilerOptions": {}
}
```

```js
// craco.config.js

const { CracoAliasPlugin } = require("react-app-alias");

module.exports = {
    plugins: [
        {
            plugin: CracoAliasPlugin,
        },
    ],

    webpack: {
        configure: (webpackConfig, { env, paths }) => {
        
            webpackConfig.output.filename = "static/js/[name].js"; 
            webpackConfig.output.assetModuleFilename = "static/media/[name].[ext]";
            webpackConfig.output.chunkFilename = "static/js/[id]-[chunkhash].js";

            webpackConfig.devtool = "eval-cheap-module-source-map";

            webpackConfig.plugins[5].options.filename = "static/css/[name].css";
            return webpackConfig;
        },
    },
};
```

### PR DESCRIPTION
**Pull request by bryanculver**
Close #95 

- Use Jest default for moduleDirectories of ['node_modules'] instead of [] when not overridden
- Use a relative path for appPath modules instead of full path which seems to be preferred for Jest

### CODE REVIEW

**Comment by oklas** [comment]
Issue with wasm https://github.com/oklas/react-app-alias/issues/95#issuecomment-1500425525 here above is solved. But issue with import is not reproducing to me.

**Comment by oklas** [comment]
Tried to rollback #97. It appears breaking. Need to inspect.

**Comment by oklas** [comment]
As I wrote above the error in ci is not reproduced locally

**Comment by bryanculver** [comment]
> As I wrote above the error in ci is not reproduced locally

Thanks. I have time on Monday to reproduce this and maybe get a sample project to demonstrate

**Pull request merged**
